name: Compile and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repo
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: resume
          path: main.pdf
  deploy_hash:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download PDF
      uses: actions/download-artifact@v2
      with:
          name: resume
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -av --progress
        path: ./main.pdf
        remote_path: /var/www/html/u/resume/${GITHUB_SHA}.pdf
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
  deploy_main:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download PDF
      uses: actions/download-artifact@v2
      with:
          name: resume
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -av --progress
        path: ./main.pdf
        remote_path: /var/www/html/u/resume.pdf
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
  deploy_latest:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download PDF
      uses: actions/download-artifact@v2
      with:
          name: resume
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -av --progress
        path: ./main.pdf
        remote_path: /var/www/html/u/resume/latest.pdf
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
