name: Compile and Deploy
on: [push]
jobs:
  build:
    runs-on: unbtun-latest
    steps:
      - name: Set up Git Repo
        uses: actions/checkout@v2
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
      - name: Deploy PDF
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -av --progress
          path: ./
          remote_path: /var/www/html/u/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
